---
name: On Push Tags 

on:
  push:
    tags:
      - v*

jobs:
  build:
    permissions: write-all
    name: print-token
    environment: dev
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        framework: [ 'net6.0-windows', 'net7.0-windows', 'net472', 'net481' ]

    env: 
      target_file: ${{ github.ref == 'refs/heads/main' && 'release' || 'nightly' }}-${{ matrix.framework }}-${{ github.ref_name }}.zip
      publish-dir: ./.publish/${{ matrix.framework }}
      project-file: ./LSLocalizeHelper/LSLocalizeHelper.csproj

    steps:
    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{ github.ref_name }}"
        echo "Tag name from GITHUB_REF##*/ :${GITHUB_REF##*/}"
        
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore Bg3LocaHelper.sln

    - name: Build
      run: dotnet build Bg3LocaHelper.sln --configuration Release --no-restore --verbosity minimal

    - name: Publish 
      run: dotnet publish ${{ env.project-file }} --configuration Release --no-build --output ${{ env.publish-dir }} --framework ${{ matrix.framework }}

    - name: Zip the publish directory
      run:  zip -r ./${{ env.target_file }} ${{ env.publish-dir }}/* 

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        if gh release view "${{ github.ref }}" > /dev/null 2>&1 ; then
          echo "Release ${{ github.ref_name }} exists"
        else
          echo "Release ${{ github.ref_name }} does not exist, creating..."
          gh release create "${{ github.ref_name }}" \
          --title="${GITHUB_REPOSITORY#*/} ${{ github.ref_name }}" \
          --generate-notes
        fi

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release upload "${{ github.ref_name }}" \
        ${{ env.target_file }}
