---
name: On Push Tags 

on:
  push:
    tags:
      - v*

jobs:
  test:
    environment: dev
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
        dotnet-framework: [ 'net6.0-windows', 'net7.0-windows', 'net472', 'net481' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup .NET ${{ matrix.dotnet-version }}
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: ${{ matrix.dotnet-version }}
#          
#      - name: Restore dependencies
#        run: dotnet restore LsLocalizeHelper.sln
#
#      - name: Build
#        run: dotnet build LsLocalizeHelper.sln --configuration Release --no-restore --verbosity minimal
#
#      - name: Test
#        run: dotnet test LsLocalizeHelper.sln --no-restore --verbosity normal
  
  build:
#    needs: test
    permissions: write-all
    name: print-token
    environment: dev
    
    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        framework: [ 'net6.0-windows', 'net7.0-windows', 'net472', 'net481' ]

    env: 
      github_ref: $env:GITHUB_REF
      framework: ${{ matrix.framework }}
      project-file: ./LsLocalizeHelper/LsLocalizeHelper.csproj
      repositoryName: $env:GITHUB_REPOSITORY.Split('/')[1]
      github_ref_name: $env:GITHUB_REF_NAME
      publish-dir: ./.publish/${{ matrix.framework }}
      releaseName: ${{ github.ref_name }}    

    steps:
    - name: Set Environment
      run: |
        $github_ref = $env:GITHUB_REF
        $framework = $env:FRAMEWORK
        $github_ref_name = $env:GITHUB_REF_NAME
        $tag = $github_ref_name

        if ($github_ref -eq 'refs/heads/main') {
            $target_file = "release-$framework-$github_ref_name.zip"
        } 
        else {
            $target_file = "nightly-$framework-$github_ref_name.zip"
        }
        
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore LsLocalizeHelper.sln

    - name: Build
      run: dotnet build LsLocalizeHelper.sln --configuration Release --no-restore --verbosity minimal

    - name: Publish 
      run: dotnet publish ${{ env.project-file }} --configuration Release --no-build --output ${{ env.publish-dir }} --framework ${{ matrix.framework }}

    - name: Zip the publish directory
      run: Compress-Archive -Path ${{ env.publish-dir }}/* -DestinationPath ./$target_file

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $repositoryName = $env:GITHUB_REPOSITORY.Split('/')[1]

        Write-Output 'ReleaseName: $releaseName'
        Write-Output 'repositoryName: repositoryName'
        Write-Output 'tag: $tag'

        if ((gh release view "$releaseName) -ne $null) {
          Write-Output 'Release $releaseName exists'
        } else {
          Write-Output 'Release $releaseName does not exist, creating...'
          gh release create '$tag' --title='$repositoryName $releaseName' --draft --prerelease --generate-notes --notes-file ./RELEASE.MD
        }

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload $tag $target_file
