---
name: On Push Tags 

on:
  push:
    tags:
      - v*

jobs:
#  test:
#    environment: dev
#    runs-on: windows-latest      
#       
#    steps:      
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup .NET ${{ matrix.dotnet-version }}
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: ${{ matrix.dotnet-version }}
#
#      - name: Restore dependencies
#        run: dotnet restore Bg3LocaHelper.sln
#
#      - name: Build
#        run: dotnet build Bg3LocaHelper.sln --configuration Release --no-restore --verbosity minimal
#
#      - name: Test
#        run: dotnet test Bg3LocaHelper.sln --no-restore --verbosity normal
  
  build:
#    needs: test 
    permissions: write-all
    name: print-token
    environment: dev
    
    runs-on: ubuntu-latest
    
    env: 
      target_file: ${{ github.ref == 'refs/heads/main' && 'release' || 'nightly' }}-${{ matrix.dotnet-framework }}-${{ github.ref_name }}.zip
      publish-dir: ./.publish/${{ matrix.dotnet-framework }}
      project-file: ./LSLocalizeHelper/LSLocalizeHelper.csproj
      
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
#        dotnet-framework: [ 'net6.0-windows', 'net7.0-windows', 'net472', 'net481' ]
        dotnet-framework: [ 'net6.0-windows' ]

    steps:
    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{ github.ref_name }}"
        echo "Tag name from GITHUB_REF##*/ :${GITHUB_REF##*/}"
        
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore Bg3LocaHelper.sln

    - name: Build
      run: dotnet build Bg3LocaHelper.sln --configuration Release --no-restore --verbosity minimal

    - name: Publish 
      run: dotnet publish ${{ env.project-file }} --configuration Release --no-build --output ${{ env.publish-dir }} --framework ${{ matrix.dotnet-framework }}

    - name: Zip the publish directory
#      run: Compress-Archive -Path ${{ env.publish-dir }}/* -DestinationPath ./${{ env.target_file }}
      run:  zip -r ./${{ env.target_file }} ${{ env.publish-dir }}/* 

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
        --repo="$GITHUB_REPOSITORY" \
        --title="${GITHUB_REPOSITORY#*/} ${{ github.ref_name }}" \
        --generate-notes \
        ${{ env.target_file }}
        
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Dieses Token wird von den GitHub Actions bereitgestellt
#      with:
#        tag_name: $new_tag
#        release_name: Release $new_tag
#        draft: false
#        prerelease: false
#    
#    - name: Upload Release Asset
#      id: upload-release-asset
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: ./${{ env.target_file }}
#        asset_name: ${{ env.target_file }}
#        asset_content_type: application/octet-stream

